begin;

-- Audit is generated by the database after an authorized admin mutation. The
-- browser cannot forge, edit, or delete these records.
create or replace function public.audit_admin_directory_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  admin_email_value text;
  target_id uuid;
  changed_fields text[] := array[]::text[];
  action_value text;
begin
  if auth.uid() is null or not public.is_admin() then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  select coalesce(au.email, 'unknown') into admin_email_value
  from auth.users au
  where au.id = auth.uid();
  admin_email_value := coalesce(admin_email_value, 'unknown');

  if tg_op = 'INSERT' then
    target_id := new.id;
    changed_fields := array['record_created'];
  elsif tg_op = 'DELETE' then
    target_id := old.id;
    changed_fields := array['record_deleted'];
  else
    target_id := new.id;
    if tg_table_name = 'users' then
      changed_fields := array_remove(array[
        case when new.name is distinct from old.name then 'name' end,
        case when new.age is distinct from old.age then 'age' end,
        case when new.nationality is distinct from old.nationality then 'nationality' end,
        case when new.vendor_id is distinct from old.vendor_id then 'vendor_id' end,
        case when new.role is distinct from old.role then 'role' end,
        case when new.is_active is distinct from old.is_active then 'is_active' end,
        case when new.induction_expiry is distinct from old.induction_expiry then 'induction_expiry' end,
        case when new.pdpa_agreed is distinct from old.pdpa_agreed then 'pdpa_agreed' end
      ], null);
    elsif tg_table_name = 'vendors' then
      changed_fields := array_remove(array[
        case when new.name is distinct from old.name then 'name' end,
        case when new.status is distinct from old.status then 'status' end
      ], null);
    end if;
  end if;

  if coalesce(cardinality(changed_fields), 0) = 0 then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  action_value := case
    when tg_table_name = 'users' and tg_op = 'INSERT' then 'ADMIN_USER_CREATED'
    when tg_table_name = 'users' and tg_op = 'DELETE' then 'ADMIN_USER_DELETED'
    when tg_table_name = 'users' and tg_op = 'UPDATE'
      and changed_fields = array['is_active']::text[]
      and (to_jsonb(old) ->> 'is_active')::boolean is distinct from false
      and (to_jsonb(new) ->> 'is_active')::boolean = false
      then 'ADMIN_USER_ARCHIVED'
    when tg_table_name = 'users' and tg_op = 'UPDATE'
      and changed_fields = array['is_active']::text[]
      and (to_jsonb(old) ->> 'is_active')::boolean = false
      and (to_jsonb(new) ->> 'is_active')::boolean = true
      then 'ADMIN_USER_REACTIVATED'
    when tg_table_name = 'users' and tg_op = 'UPDATE'
      and changed_fields = array['induction_expiry']::text[]
      and to_jsonb(new) ->> 'induction_expiry' is null
      then 'ADMIN_INDUCTION_RESET'
    when tg_table_name = 'users' then 'ADMIN_USER_UPDATED'
    when tg_table_name = 'vendors' and tg_op = 'INSERT' then 'ADMIN_VENDOR_CREATED'
    when tg_table_name = 'vendors' and tg_op = 'DELETE' then 'ADMIN_VENDOR_DELETED'
    when tg_table_name = 'vendors' and tg_op = 'UPDATE'
      and changed_fields = array['status']::text[]
      and to_jsonb(new) ->> 'status' = 'REJECTED'
      then 'ADMIN_VENDOR_ARCHIVED'
    else 'ADMIN_VENDOR_UPDATED'
  end;

  insert into public.audit_logs(admin_email, action, target, details)
  values (
    admin_email_value,
    action_value,
    tg_table_name || ':' || target_id::text,
    jsonb_build_object(
      'operation', tg_op,
      'changed_fields', to_jsonb(changed_fields),
      'values_recorded', false
    )::text
  );

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

revoke all on function public.audit_admin_directory_mutation()
  from public, anon, authenticated;

drop trigger if exists trg_audit_admin_user_mutation on public.users;
create trigger trg_audit_admin_user_mutation
after insert or update or delete on public.users
for each row execute function public.audit_admin_directory_mutation();

drop trigger if exists trg_audit_admin_vendor_mutation on public.vendors;
create trigger trg_audit_admin_vendor_mutation
after insert or update or delete on public.vendors
for each row execute function public.audit_admin_directory_mutation();

-- Destructive UI actions become reversible archives. Existing linked exam,
-- permit, access, and audit history remains attached to the original row.
create or replace function public.admin_archive_user(user_id_param uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_user public.users%rowtype;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;

  select * into target_user
  from public.users
  where id = user_id_param
  for update;
  if target_user.id is null then raise exception 'User not found'; end if;
  if target_user.role = 'ADMIN' then raise exception 'Admin accounts cannot be archived here'; end if;

  update public.users
  set is_active = false
  where id = user_id_param and is_active is distinct from false;

  return jsonb_build_object(
    'archived', true,
    'user_id', target_user.id,
    'history_preserved', true,
    'already_inactive', target_user.is_active = false
  );
end;
$$;
revoke all on function public.admin_archive_user(uuid) from public, anon;
grant execute on function public.admin_archive_user(uuid) to authenticated, service_role;

create or replace function public.admin_archive_vendor(vendor_id_param uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_vendor public.vendors%rowtype;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;

  select * into target_vendor
  from public.vendors
  where id = vendor_id_param
  for update;
  if target_vendor.id is null then raise exception 'Vendor not found'; end if;

  update public.vendors
  set status = 'REJECTED'
  where id = vendor_id_param and status is distinct from 'REJECTED';

  return jsonb_build_object(
    'archived', true,
    'vendor_id', target_vendor.id,
    'links_preserved', true,
    'already_rejected', target_vendor.status = 'REJECTED'
  );
end;
$$;
revoke all on function public.admin_archive_vendor(uuid) from public, anon;
grant execute on function public.admin_archive_vendor(uuid) to authenticated, service_role;

-- Reads remain unchanged. All high-integrity writes must use their authorized
-- security-definer RPC, which keeps validation and audit in one transaction.
revoke insert, update, delete on table public.vendors from anon, authenticated;
revoke insert, update, delete on table public.audit_logs from anon, authenticated;
revoke delete on table public.users from anon, authenticated;
revoke insert, update, delete on table public.questions from anon, authenticated;
revoke insert, update, delete on table public.question_revisions from anon, authenticated;
revoke insert, update, delete on table public.system_config from anon, authenticated;
revoke insert, update, delete on table public.exam_history from anon, authenticated;
revoke insert, update, delete on table public.exam_logs from anon, authenticated;
revoke insert, update, delete on table public.work_permits from anon, authenticated;
revoke insert, update, delete on table public.user_training_access from anon, authenticated;
revoke insert, update, delete on table public.supplier_outsource_passes from anon, authenticated;

commit;
